Repository googleinterns/tagpost, pull requests merged in 2020-08, with the labels that each got.

#26 In Envoy proxy, get backend address from environment variables.
  third_party/envoy/BUILD
  third_party/envoy/config/etc/envoy/envoy.template.yaml
  third_party/envoy/config/opt/bootstrap/start_envoy.sh
Labels: cla: yes

#37 Use chart to show TagStat
  ui/src/app/google-chart/donut-chart/donut-chart.component.html
  ui/src/app/google-chart/donut-chart/donut-chart.component.sass
  ui/src/app/google-chart/donut-chart/donut-chart.component.ts
  ui/src/app/google-chart/google-chart.module.ts
  ui/src/app/google-chart/google-chart.service.ts
  ui/src/app/panel/thread-detail/thread-detail.component.html
  ui/src/app/panel/thread-detail/thread-detail.component.ts
  ui/src/app/panel/thread-list/thread-list.component.html
  ui/src/app/service/data.service.ts
Labels: cla: yes, frontend

#39 Set primaryTag for tagStats
  src/java/com/google/tagpost/TagpostClient.java
  src/java/com/google/tagpost/spanner/SpannerService.java
Labels: backend, bug, cla: yes

#41 Add try_files in nginx config to serve up index.html
  ui/nginx_conf/default.conf.template
Labels: cla: yes

#40 set default bazel version to 3.3.1
  .bazelversion
Labels: cla: yes

#42 Update tests for TagpostClient
  src/javatests/com/google/tagpost/BUILD
  src/javatests/com/google/tagpost/TagpostClientTest.java
Labels: backend, cla: yes

#43 order result from database by timestamp
  src/java/com/google/tagpost/spanner/SpannerService.java
Labels: cla: yes

#38 Implement frontend functionality to add new comments
  src/java/com/google/tagpost/spanner/SpannerService.java
  ui/src/app/app.module.ts
  ui/src/app/panel/comment-form/comment-form.component.html
  ui/src/app/panel/comment-form/comment-form.component.sass
  ui/src/app/panel/comment-form/comment-form.component.spec.ts
  ui/src/app/panel/comment-form/comment-form.component.ts
  ui/src/app/panel/thread-detail/thread-detail.component.html
  ui/src/app/panel/thread-detail/thread-detail.component.ts
  ui/src/app/search-bar/search-bar.component.html
  ui/src/app/search-bar/search-bar.component.sass
  ui/src/app/search-bar/search-bar.component.ts
  ui/src/app/service/data.service.ts
Labels: cla: yes, frontend

#44 frontend fix
  ui/src/app/app-routing.module.ts
  ui/src/app/app.module.ts
  ui/src/app/panel/comment-form/comment-form.component.html
  ui/src/app/panel/comment-form/comment-form.component.ts
  ui/src/app/panel/modal/modal.component.html
  ui/src/app/panel/modal/modal.component.sass
  ui/src/app/panel/modal/modal.component.ts
  ui/src/app/panel/panel.component.html
  ui/src/app/panel/panel.component.sass
  ui/src/app/panel/thread-detail/thread-detail.component.html
  ui/src/app/panel/thread-detail/thread-detail.component.ts
  ui/src/app/panel/thread-list/thread-list.component.html
  ui/src/app/panel/thread-list/thread-list.component.sass
  ui/src/app/panel/thread-list/thread-list.component.ts
  ui/src/app/panel/welcome/welcome.component.html
  ui/src/app/panel/welcome/welcome.component.sass
  ui/src/app/panel/welcome/welcome.component.spec.ts
  ui/src/app/panel/welcome/welcome.component.ts
  ui/src/app/search-bar/search-bar.component.html
  ui/src/app/search-bar/search-bar.component.sass
  ui/src/app/search-bar/search-bar.component.ts
  ui/src/app/service/data.service.ts
  ui/src/app/tool-bar/tool-bar.component.html
Labels: cla: yes

#45 Update README.md
  README.md
Labels: cla: yes
