Repository googleinterns/tagpost, pull requests merged in 2020-07, with the labels that each got.

#20 Add gRPC to UI
  WORKSPACE
  make_ts_proto.sh
  src/proto/BUILD
  ui/README.md
  ui/angular.json
  ui/package.json
  ui/src/.gitignore
  ui/src/main.ts
  ui/tsconfig.base.json
  ui/tsconfig.json
  ui/yarn.lock
Labels: cla: yes

#22 Config import order in tslint
  ui/e2e/src/app.e2e-spec.ts
  ui/src/app/app-routing.module.ts
  ui/src/app/app.component.spec.ts
  ui/src/app/app.module.ts
  ui/src/main.ts
  ui/src/test.ts
  ui/tslint.json
Labels: cla: yes

#23 Unify configs between backend server and Envoy proxy
  .gitignore
  BUILD
  common_def.bzl
  src/java/com/google/tagpost/BUILD
  src/java/com/google/tagpost/TagpostServer.java
  third_party/envoy/BUILD
  third_party/envoy/config/etc/envoy/envoy.template.yaml
  third_party/envoy/config/opt/bootstrap/start_envoy.sh
  ui/src/main.ts
Labels: cla: yes

#24 set up frontend layout
  ui/angular.json
  ui/package.json
  ui/src/app/app.component.html
  ui/src/app/app.module.ts
  ui/src/app/panel/panel.component.html
  ui/src/app/panel/panel.component.sass
  ui/src/app/panel/panel.component.spec.ts
  ui/src/app/panel/panel.component.ts
  ui/src/app/search-bar/search-bar.component.html
  ui/src/app/search-bar/search-bar.component.sass
  ui/src/app/search-bar/search-bar.component.spec.ts
  ui/src/app/search-bar/search-bar.component.ts
  ui/src/app/tool-bar/tool-bar.component.html
  ui/src/app/tool-bar/tool-bar.component.sass
  ui/src/app/tool-bar/tool-bar.component.spec.ts
  ui/src/app/tool-bar/tool-bar.component.ts
  ui/src/index.html
Labels: cla: yes, frontend

#27 Update yarn.lock
  ui/yarn.lock
Labels: cla: yes

#28 Setup frontend server and UI
  ui/Dockerfile
  ui/make_docker_image.sh
  ui/nginx_conf/default.conf.template
  ui/nginx_conf/start_nginx.sh
  ui/src/main.ts
Labels: cla: yes

#29 Implement frontend search functionality
  ui/src/app/app.component.spec.ts
  ui/src/app/app.component.ts
  ui/src/app/data.service.spec.ts
  ui/src/app/data.service.ts
  ui/src/app/panel/panel.component.html
  ui/src/app/panel/panel.component.spec.ts
  ui/src/app/panel/panel.component.ts
  ui/src/app/search-bar/search-bar.component.html
  ui/src/app/search-bar/search-bar.component.spec.ts
  ui/src/app/search-bar/search-bar.component.ts
  ui/src/app/tool-bar/tool-bar.component.spec.ts
  ui/src/app/tool-bar/tool-bar.component.ts
  ui/src/environments/environment.ts
Labels: cla: yes, frontend

#32 Modify add thread operation to allow adding thread with a new tag
  src/java/com/google/tagpost/TagpostClient.java
  src/java/com/google/tagpost/spanner/SpannerService.java
  src/proto/tagpost.proto
  src/proto/tagpost_rpc.proto
Labels: backend, cla: yes

#33 modify fetch thread to include Timestamp and Topic
  src/java/com/google/tagpost/spanner/SpannerService.java
Labels: backend, cla: yes

#34 Add routing on the panel to allow navigation of individual thread
  ui/src/app/app-routing.module.ts
  ui/src/app/app.component.html
  ui/src/app/app.component.spec.ts
  ui/src/app/app.module.ts
  ui/src/app/panel/modal/modal.component.html
  ui/src/app/panel/modal/modal.component.sass
  ui/src/app/panel/modal/modal.component.spec.ts
  ui/src/app/panel/modal/modal.component.ts
  ui/src/app/panel/panel.component.html
  ui/src/app/panel/panel.component.spec.ts
  ui/src/app/panel/panel.component.ts
  ui/src/app/search-bar/search-bar.component.spec.ts
  ui/src/app/search-bar/search-bar.component.ts
  ui/src/app/service/data.service.spec.ts
  ui/src/app/service/data.service.ts
  ui/src/app/tool-bar/tool-bar.component.spec.ts
Labels: cla: yes, frontend
